config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  root to: 'articles#index'

  resources :articles do
    resources :comments
  end

  get 'my_articles', to: 'articles#my_articles'
  get 'users', to: 'users#index'
  get 'user/:id/profile', to: 'users#profile', as: 'profile'
  put 'notifications/:id/user', to: 'notifications#mark_as_read'

  post 'follow/user', to: 'followers#create', as: "follow_user"
  delete 'follow/user', to: 'followers#destroy', as: "follow_userr"

  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :body, presence: true

  default_scope { order(created_at: :desc) }

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :body, presence: true

end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  
  belongs_to :user

  default_scope { where(read: false) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :articles
  has_many :notifications

  validates :email, uniqueness: true, allow_blank: true

  validates :first_name, :last_name, :email, presence: true

  scope :not_current_user, ->(id) { where.not("id = ?", id) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.find_by_query(query)
    User.where("first_name LIKE ? OR last_name LIKE ?", "%#{query}%", "%#{query}%")
  end

  def followers
    Follower.where("user_id = ?", self.id)
  end

  def avatar
    self.gender == "M" ? "https://image.ibb.co/gTG79k/male.png" : "https://image.ibb.co/gVyyFQ/female.jpg"
  end

  def is_following(user)
    Follower.where("user_id = ? AND followed_by = ?", user.id, self.id).count == 0 ? false : true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :gender])
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, only: [:show, :destroy, :update, :edit]

  def index
    @articles = Article.all.order(created_at: "desc")
  end

  def my_articles
    @articles = Article.where("user_id = ?", current_user.id).order(created_at: "desc")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article has been created"
      redirect_to articles_path
    else
      flash[:danger] = "Article has not been created"
      render :new
    end
  end

  def show
    if @article.nil?
      flash[:alert] = "The article you are looking for could not be found"
      redirect_to articles_path
    else
      @comment = @article.comments.build
      @comments = @article.comments
    end
  end

  def edit
    unless @article.user.id == current_user.id
      flash.now[:alert] = "You can only edit your own articles"
      redirect_to root_path
    end
  end

  def update
    unless @article.user.id == current_user.id
      flahs.now[:alert] = "You can only edit your own articles"
      redirect_to root_path
    else
      if @article.update(article_params)
        flash[:notice] = "Article has been updated"
        redirect_to root_path
      else
        flash.now[:danger] = "Article has not been updated"
        render :edit
      end
    end
  end

  def destroy
    if @article.user.id == current_user.id
      if @article.destroy
        flash[:notice] = "The Article has been deleted"
      else
        flash[:alert] = "The Article could not be deleted"
      end
    else
      flash[:alert] = "You can only delete your own articles"
    end
    redirect_to root_path
  end

  private

    def set_article
      @article = Article.find_by(id: params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_article

  def create
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
      flash.now[:notice] = "Comment has been created"
    else
      flash.now[:alert] = "Comment has not been created"
      render current_path
    end

  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_article
      @article = Article.find_by(id: params[:article_id])
    end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

    before_action :authenticate_user!
    before_action :set_user, only: [ :create ]

    def create
        unless is_already_following
            @follower = Follower.new(user_id: params[:user_id], followed_by: current_user.id)
            if @follower.save
                @following = true;
                user = User.find(params[:user_id])
                notification = user.notifications.build
                notification.description = "You started to be followed by #{current_user.first_name}"
                notification.save
            else
                return false
            end
        else
            @following = false
            @follower = Follower.find_by("user_id = ? AND followed_by = ? ", params[:user_id], current_user.id)
            @follower.destroy
        end
    end

    private

        def is_already_following
            current_user.is_following(@user)
        end

        def set_user
           @user = User.find(params[:user_id])
        end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

    skip_before_action :verify_authenticity_token    

    def mark_as_read
        notifications = Notification.where(user_id: params[:id])
        notifications.each do |notification| 
            notification.update(read: true)
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :authenticate_user!, only: [ :index ]
    before_action :set_user, only: [ :profile ]

    def index
        render json: { data: query_response }, status: :ok
    end

    def profile
        unless @user
            flash.now[:alert] = "User not found"
        end
    end

    private

        def query_response
            users = User.find_by_query(params[:query])
            data = []
            users.each do |user|
                data << {
                    full_name: user.full_name,
                    url_profile: "/user/#{user.id}/profile"
                } 
            end if users.any?
            data
        end

        def set_user
            @user = User.find(params[:id])
        end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

    def persisted_comments(comments)
        comments.reject{ |comment| comment.new_record? }
    end

end

app/views/articles/_article.html.erb
<div <%= view_profile ? raw("class='column margin-bottom-message'") : raw("class='column'") %> >
    <div class="ui fluid card">
        <div class="content">
        <div class="right floated meta"><%= time_ago_in_words(article.created_at) %></div>
            <%= image_tag article.user.avatar, class: "ui avatar image" %>
            <%= view_profile ? article.user.full_name : truncate(article.user.full_name, length: 15) %>
        </div>
        <div class="image">
        <a href=<%= "/articles/#{article.id}" %> class="header">
            <h1 class="ui wireframe"><%= truncate(article.title, length: 50) %></h1>
        </a>
        </div>
        <div class="content">
        <i class="comment icon"></i>
            <%= pluralize(article.comments.count, "comment") %>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, multipart: true, :html => {class: "ui form", role: "form"}) do |f| %>
    <% if @article.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@article.errors.count, "error") %>
              prohibited this article from being saved: </h2>
              <div class="panel-body">
                <ul>
                  <% @article.errors.full_messages.each do |msg| %>
                  <li>
                    <%= msg %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
    <% end %>

    <div class='field'>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Title of article', autofocus: true, required: "true" %>
    </div>

    <div class='field'>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 30, id: "descricaoText", placeholder: 'Body of article', required: "true" %>
    </div>

    <div class='field'>
      <%= f.submit class: 'ui button' %>
    </div>

<% end %>

app/views/articles/edit.html.erb
<h3 class='text-center'>Editing an Article</h3>

<%= render 'form' %>

app/views/articles/index.html.erb
<% if @articles.empty? %>
  <h1 id="no-articles">No Articles Created</h1>
<% else %>

  <div class="ui four column grid">

    <% @articles.each do |article| %>

      <%= render "article", article: article, view_profile: false %>

    <% end %>

  </div>

<% end %>

app/views/articles/my_articles.html.erb
<h2>My Articles</h2><br/>

<table class="ui very basic table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= link_to raw("<i class='edit icon'></i>"), edit_article_path(article) %></td>
            <td><%= link_to raw("<i class='erase icon'></i>"), article_path(article), class: "erase-link",
                                                                                      method: :delete,
                                                                                      :data => {:confirm => 'Are you sure?'} %>
                                                                                      </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h3 class='text-center'>Adding New Article</h3>

<%= render 'form' %>

app/views/articles/show.html.erb
<section class="article cotainer">

  <header>
    <h1 class="ui header"><%= @article.title %></h1><br/><br/>
  </header>

  <div class="article body">
    <%= @article.body %>
  </div>

    <div class="ui comments">

      <h3 class="ui dividing header">Comments</h3>

      <% if @article.comments.any? %>

        <div id="comments">

          <% persisted_comments(@comments).each do |comment| %>

            <%= render 'comments/comment', comment: comment %>

          <% end %>

        </div>

      <% end %>

      <% if user_signed_in? %>

          <%= form_for [@article, @comment], remote: true, :html => { class: "ui form margin-top" } do |f| %>

            <div class="field">
              <%= f.label :body, "New Comment" %>
              <%= f.text_area :body %>
            </div>

            <div class="field">
              <%= f.submit class: "ui button" %>
            </div>

          <% end %>

      <% end %>

    </div>

</section>

app/views/comments/_comment.html.erb
<div class="comment">
  <a class="avatar">
    <%= image_tag comment.user.avatar %>
  </a>
  <div class="content">
    <a class="author"><%= comment.user.full_name %></a>
    <div class="metadata">
       <span class="date"><%= time_ago_in_words(comment.created_at) %></span>
    </div>
    <div class="text">
       <%= comment.body %>
    </div>
  </div>
</div>

app/views/followers/_error_messages.html.erb
<% if @follower.errors.any? %>
    <ul>
        <% @follower.errors.full_messages.each do |message| %>
            <li class="margin-bottom-message ui message error"><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/followers/create.js.erb
<% if @follower.errors.any? %>
  $("#error_messages_ajax").show().html("<%=  escape_javascript(render 'error_messages')%>");
<% else %>    
  var form = document.querySelector("#follow-form");
  var div = document.querySelector("button.ui.basic.button");

  <% if @following %>
    div.textContent = "Following";
    div.classList.remove("green");
    div.classList.add("blue");
  <% else %>
    div.textContent = "Follow";
    div.classList.remove("blue");
    div.classList.add("green");
  <% end %>

  $("#followers").replaceWith("<%=  escape_javascript(render 'users/followers', user: @user)%>");
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render "shared/menu" %>

    <div class="ui container" style="margin-top: 5em;">
        <div class="row">
          <div class="col-md-12">
            <% flash.each do |key, message| %>
              <div class="margin-bottom-message ui message <%= key == 'notice'? 'success': 'error' %>">
                <i class="close icon"></i>
                <%= message %>
              </div>
            <% end %>
          </div>
        </div>
        <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_menu.html.erb
<div class="ui fixed inverted borderless menu">
  <%= link_to 'BlogCapenga', root_path, class: "header item active" %>
  <div class="right menu">
    <% if user_signed_in? %>
      <input type="hidden" data-user="<%= current_user.id %>">
      <div class="ui fluid category item search">
        <div class="ui icon transparent inverted input">
          <input class="prompt" type="text" placeholder="Search users...">
          <i class="search icon"></i>
        </div>
        <div class="results"></div>
      </div>
      <div class="ui dropdown item">
        <div style="padding: 0px 8px 0px 8px;">
          <sup><%= current_user.notifications.count %></sup><i class="alarm icon"></i>
        </div>
        <div class="menu">
          <% if current_user.notifications.any? %>
            <% current_user.notifications.each do |notification| %>
              <div class="item"><%= notification.description %></div>
            <% end %>  
          <% else %>
            <div class="item">No news</div>
          <% end %>  
        </div>
      </div>
      <div class="ui dropdown item" id="menu-item-dropdown">
        <%= current_user.email %>
        <div class="i dropdown icon"></div>
        <div class="menu">
          <%= link_to raw("<i class='add square icon'></i> New Article"), new_article_path, class: "item" %>
          <%= link_to raw("<i class='file text outline icon'></i> My Articles"), my_articles_path, class: "item" %>
          <%= link_to raw("<i class='user icon'></i> Perfil"), profile_path(current_user), class: "item" %>
          <%= link_to raw("<i class='power icon'></i> Logout"), destroy_user_session_path, method: :delete, class: "item" %>
        </div>
      </div>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, class: "item ui button bordless" %>
    <% end %>
  </div>
</div>

app/views/users/_followers.html.erb
<span id="followers">
    <i class="comment icon"></i>
    <%= pluralize(user.followers.count, "follower") %>
</span>

app/views/users/profile.html.erb
<div class="ui grid">
    
    <div class="four wide column">

        <div class="ui card">
            <div class="image">
                <%= image_tag @user.avatar %>
            </div>
            <div class="content">
                <div class="header">
                    <%= @user.full_name %>
                </div>
            </div>
            <div class="content">
                <%= render 'followers', user: @user %>
                <% unless @user.id == current_user.id %>
                    <form action="/follow/user" method="post" accept-charset="UTF-8" data-remote="true" id="follow-form">
                        <input type="hidden" name="user_id" value=<%= "#{@user.id}" %>>
                        <button <%=  current_user.is_following(@user) ? raw("class='ui basic blue button right floated'") : 
                                                                        raw("class='ui basic green button right floated'") %>>
                            <%=  current_user.is_following(@user) ? "Following" : "Follow" %>
                        </button>
                    </form>
                <% else %>
                    <%= link_to raw("<i class='pencil icon'></i> Perfil"), edit_user_registration_path, class: "ui button primary right floated" %>
                <% end %>
            </div>
        </div>
        
    </div>

    <div class="twelve wide column">

        <div id="error_messages_ajax"></div>

        <% @user.articles.each do |article| %>

            <%= render "articles/article", article: article, view_profile: true %>

        <% end %>

    </div>

</div>